name: Build and Release KernelSU Next Image

on:
  push:
    tags:
      - '**'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 240

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache ca-certificates clang curl flex gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi git libelf-dev libssl-dev lld llvm make python3 rsync unzip wget zip zstd

      - name: Make build script executable
        run: chmod +x ./build.sh&&chmod +x ./scripts/repack

      - name: Build kernel
        env:
          OUT_DIR: ${{ github.workspace }}/out
          DIST_DIR: ${{ github.workspace }}/out
          ARCH: arm64
          PLATFORM_VERSION: "12"
          LTO: thin
          CROSS_COMPILE: aarch64-linux-gnu-
          CROSS_COMPILE_COMPAT: arm-linux-gnueabi-
          LD: ld.lld
          HOSTLD: ld.lld
          AR: llvm-ar
          NM: llvm-nm
          MAKEFLAGS: -j2
        run: |
          ./build.sh

      - name: Build Image
        env:
          OUT_DIR: ${{ github.workspace }}/out
        run: |
          ./scripts/repack

      - name: Upload build output as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernelsunext-build-zips
          path: |
            release/*.tar
          if-no-files-found: error
          retention-days: 14

      - name: Create GitHub Release and Upload Assets
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/*.tar
          name: KernelSUNext ${{ env.REL_KERNEL }} SUSFS ${{ env.REL_SUSFS }} A155FXXS7CYG1 A155FXXS7CYG4
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}